---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: koti-deploymentss11
spec:
 replicas: 1
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: koti-kotiss11
 template:
  metadata:
   name: koti-kotipodss11
   labels:
     app: koti-kotiss11	 
  spec: 
    containers:
    - name: koti-kotiss11
      image: newmynodejsimage11
      imagePullPolicy: Always
      ports:
      - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
 name: koti-servicess11
spec:
  type: NodePort
  selector:
   app: koti-kotiss11
  ports:
   - port: 3000
     targetPort: 3000
...
